In [19]:
import pandas as pd
import datetime
import numpy as np
import matplotlib.pyplot as plt
from pandas_datareader import data
%matplotlib inline

dash = pd.read_csv('/home/ml/datasets/DASH60_with_indicators.csv',delimiter=',')
dash.head()

,Date_Time,Open,Max,Min,Close,Volume,SMA14,SMA30,EMA14,EMA30,...,BB_Lower,BB_Mean,BB_Upper,EMA_12,EMA_26,MACD,RSI,ATR,PSAR,Direction
0,2017-09-08 14:00:00,335.93,335.93,293.66,322.16,274,329.045000,329.045000,328.553214,328.815500,...,101.142356,329.045000,556.947644,328.471250,328.780192,-0.308942,0.000000,41.508571,362.790000,1.0
1,2017-09-08 15:00:00,322.16,326.39,307.20,323.87,241,327.320000,327.320000,326.764211,327.055920,...,151.648753,327.320000,502.991247,326.675381,327.016008,-0.340627,11.464539,34.885178,362.790000,1.0
2,2017-09-08 16:00:00,324.00,335.90,324.00,331.37,137,328.332500,328.332500,328.173251,328.244606,...,177.269220,328.332500,479.395780,328.157289,328.233194,-0.075905,40.983275,28.853749,360.024800,-1.0
3,2017-09-08 17:00:00,331.37,331.54,320.73,320.73,121,326.812000,326.812000,326.231319,326.534851,...,173.684598,326.812000,479.939402,326.139321,326.493172,-0.353851,28.026697,24.336618,357.370208,-1.0
4,2017-09-08 18:00:00,320.73,326.43,320.00,320.00,77,325.676667,325.676667,324.789503,325.256411,...,174.034308,325.676667,477.319026,324.647143,325.192642,-0.545499,27.412390,20.616776,354.821800,-1.0

In [20]:
dash.columns

Index(['Date_Time', 'Open', 'Max', 'Min', 'Close', 'Volume', 'SMA14', 'SMA30',
       'EMA14', 'EMA30', 'Privot_Dot', 'Pct_Change', 'TR', 'R1', 'R2', 'R3',
       'S1', 'S2', 'S3', 'BB_Lower', 'BB_Mean', 'BB_Upper', 'EMA_12', 'EMA_26',
       'MACD', 'RSI', 'ATR', 'PSAR', 'Direction'],
      dtype='object')

In [77]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler

n_train = (dash['Date_Time'].count()*0.7).astype(int)

X = dash[['Volume', 'SMA30',
       'EMA14', 'EMA30', 'Privot_Dot', 'Pct_Change', 'TR', 'R1', 'R2', 'R3',
       'S1', 'S2', 'S3', 'BB_Lower', 'BB_Mean', 'BB_Upper', 'EMA_12', 'EMA_26',
       'MACD', 'RSI', 'ATR', 'PSAR']]
y = dash['Direction']

X_train, X_test = X[:n_train], X[n_train:]
y_train, y_test = y[:n_train], y[n_train:] 

pipe = Pipeline([("scaler", MinMaxScaler()),("mlp",MLPClassifier(solver='lbfgs', random_state=0, hidden_layer_sizes=[10]))])

In [78]:
from sklearn.model_selection import GridSearchCV

param_grid = {'mlp__activation':['tanh', 'relu', 'logistic'],
             'mlp__alpha':[0.0001, 0.001, 0.01, 0.1, 1, 10]}

grid = GridSearchCV(pipe, param_grid, cv=5)
grid.fit(X_train, y_train)
print("Beste Genauigkeit nach Kreuzvalidierung: {:.2f}".format(grid.best_score_))
print("Bester Score auf den Testdaten: {:.2f}".format(grid.score(X_test, y_test)))
print("Beste Parameter: {}".format(grid.best_params_))

Beste Genauigkeit nach Kreuzvalidierung: 0.51
Bester Score auf den Testdaten: 0.54
Beste Parameter: {'mlp__activation': 'tanh', 'mlp__alpha': 0.1}